//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("lrModel", "FK_PageContents_Contact", "Contact", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Web_LR.Models.Contact), "PageContents", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.PageContents), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_Header_Culture", "Culture", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.Culture), "Header", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.Header), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_Menu_PageRoute", "Culture", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.Culture), "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.Menu), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_PageRoute_Culture", "Culture", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.Culture), "PageRoute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.PageRoute), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_Header_Header", "HeaderClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.HeaderClasses), "Header", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.Header), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_Menu_PageRoute1", "PageRoute", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.PageRoute), "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.Menu), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_PageContents_PageContentClasses", "PageContentClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.PageContentClasses), "PageContents", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.PageContents), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_PageContents_PageContentType", "PageContentType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.PageContentType), "PageContents", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.PageContents), true)]
[assembly: EdmRelationshipAttribute("lrModel", "FK_PageContents_PageRoute", "PageRoute", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Web_LR.Models.PageRoute), "PageContents", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web_LR.Models.PageContents), true)]

#endregion

namespace Web_LR.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class lrEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new lrEntities object using the connection string found in the 'lrEntities' section of the application configuration file.
        /// </summary>
        public lrEntities() : base("name=lrEntities", "lrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new lrEntities object.
        /// </summary>
        public lrEntities(string connectionString) : base(connectionString, "lrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new lrEntities object.
        /// </summary>
        public lrEntities(EntityConnection connection) : base(connection, "lrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contact> Contact
        {
            get
            {
                if ((_Contact == null))
                {
                    _Contact = base.CreateObjectSet<Contact>("Contact");
                }
                return _Contact;
            }
        }
        private ObjectSet<Contact> _Contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Culture> Culture
        {
            get
            {
                if ((_Culture == null))
                {
                    _Culture = base.CreateObjectSet<Culture>("Culture");
                }
                return _Culture;
            }
        }
        private ObjectSet<Culture> _Culture;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Header> Header
        {
            get
            {
                if ((_Header == null))
                {
                    _Header = base.CreateObjectSet<Header>("Header");
                }
                return _Header;
            }
        }
        private ObjectSet<Header> _Header;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HeaderClasses> HeaderClasses
        {
            get
            {
                if ((_HeaderClasses == null))
                {
                    _HeaderClasses = base.CreateObjectSet<HeaderClasses>("HeaderClasses");
                }
                return _HeaderClasses;
            }
        }
        private ObjectSet<HeaderClasses> _HeaderClasses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PageContentClasses> PageContentClasses
        {
            get
            {
                if ((_PageContentClasses == null))
                {
                    _PageContentClasses = base.CreateObjectSet<PageContentClasses>("PageContentClasses");
                }
                return _PageContentClasses;
            }
        }
        private ObjectSet<PageContentClasses> _PageContentClasses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PageContents> PageContents
        {
            get
            {
                if ((_PageContents == null))
                {
                    _PageContents = base.CreateObjectSet<PageContents>("PageContents");
                }
                return _PageContents;
            }
        }
        private ObjectSet<PageContents> _PageContents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PageContentType> PageContentType
        {
            get
            {
                if ((_PageContentType == null))
                {
                    _PageContentType = base.CreateObjectSet<PageContentType>("PageContentType");
                }
                return _PageContentType;
            }
        }
        private ObjectSet<PageContentType> _PageContentType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PageRoute> PageRoute
        {
            get
            {
                if ((_PageRoute == null))
                {
                    _PageRoute = base.CreateObjectSet<PageRoute>("PageRoute");
                }
                return _PageRoute;
            }
        }
        private ObjectSet<PageRoute> _PageRoute;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContact(Contact contact)
        {
            base.AddObject("Contact", contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Culture EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCulture(Culture culture)
        {
            base.AddObject("Culture", culture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Header EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHeader(Header header)
        {
            base.AddObject("Header", header);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HeaderClasses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHeaderClasses(HeaderClasses headerClasses)
        {
            base.AddObject("HeaderClasses", headerClasses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PageContentClasses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPageContentClasses(PageContentClasses pageContentClasses)
        {
            base.AddObject("PageContentClasses", pageContentClasses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PageContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPageContents(PageContents pageContents)
        {
            base.AddObject("PageContents", pageContents);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PageContentType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPageContentType(PageContentType pageContentType)
        {
            base.AddObject("PageContentType", pageContentType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PageRoute EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPageRoute(PageRoute pageRoute)
        {
            base.AddObject("PageRoute", pageRoute);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Contact CreateContact(global::System.Int32 id, global::System.String name, global::System.String phone, global::System.String email)
        {
            Contact contact = new Contact();
            contact.Id = id;
            contact.Name = name;
            contact.Phone = phone;
            contact.Email = email;
            return contact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_Contact", "PageContents")]
        public EntityCollection<PageContents> PageContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PageContents>("lrModel.FK_PageContents_Contact", "PageContents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PageContents>("lrModel.FK_PageContents_Contact", "PageContents", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="Culture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Culture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Culture object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="culture1">Initial value of the Culture1 property.</param>
        public static Culture CreateCulture(global::System.Int32 id, global::System.String culture1)
        {
            Culture culture = new Culture();
            culture.Id = id;
            culture.Culture1 = culture1;
            return culture;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Culture1
        {
            get
            {
                return _Culture1;
            }
            set
            {
                OnCulture1Changing(value);
                ReportPropertyChanging("Culture1");
                _Culture1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Culture1");
                OnCulture1Changed();
            }
        }
        private global::System.String _Culture1;
        partial void OnCulture1Changing(global::System.String value);
        partial void OnCulture1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CultureName
        {
            get
            {
                return _CultureName;
            }
            set
            {
                OnCultureNameChanging(value);
                ReportPropertyChanging("CultureName");
                _CultureName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CultureName");
                OnCultureNameChanged();
            }
        }
        private global::System.String _CultureName;
        partial void OnCultureNameChanging(global::System.String value);
        partial void OnCultureNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Header_Culture", "Header")]
        public EntityCollection<Header> Header
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Header>("lrModel.FK_Header_Culture", "Header");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Header>("lrModel.FK_Header_Culture", "Header", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Menu_PageRoute", "Menu")]
        public EntityCollection<Menu> Menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("lrModel.FK_Menu_PageRoute", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("lrModel.FK_Menu_PageRoute", "Menu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageRoute_Culture", "PageRoute")]
        public EntityCollection<PageRoute> PageRoute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PageRoute>("lrModel.FK_PageRoute_Culture", "PageRoute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PageRoute>("lrModel.FK_PageRoute_Culture", "PageRoute", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="Header")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Header : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Header object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isImage">Initial value of the IsImage property.</param>
        /// <param name="culture">Initial value of the Culture property.</param>
        /// <param name="class">Initial value of the Class property.</param>
        public static Header CreateHeader(global::System.Int32 id, global::System.Boolean isImage, global::System.Int32 culture, global::System.Int32 @class)
        {
            Header header = new Header();
            header.Id = id;
            header.IsImage = isImage;
            header.Culture = culture;
            header.Class = @class;
            return header;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsImage
        {
            get
            {
                return _IsImage;
            }
            set
            {
                OnIsImageChanging(value);
                ReportPropertyChanging("IsImage");
                _IsImage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsImage");
                OnIsImageChanged();
            }
        }
        private global::System.Boolean _IsImage;
        partial void OnIsImageChanging(global::System.Boolean value);
        partial void OnIsImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageHref
        {
            get
            {
                return _ImageHref;
            }
            set
            {
                OnImageHrefChanging(value);
                ReportPropertyChanging("ImageHref");
                _ImageHref = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageHref");
                OnImageHrefChanged();
            }
        }
        private global::System.String _ImageHref;
        partial void OnImageHrefChanging(global::System.String value);
        partial void OnImageHrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Culture
        {
            get
            {
                return _Culture;
            }
            set
            {
                OnCultureChanging(value);
                ReportPropertyChanging("Culture");
                _Culture = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Culture");
                OnCultureChanged();
            }
        }
        private global::System.Int32 _Culture;
        partial void OnCultureChanging(global::System.Int32 value);
        partial void OnCultureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.Int32 _Class;
        partial void OnClassChanging(global::System.Int32 value);
        partial void OnClassChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Header_Culture", "Culture")]
        public Culture Culture1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_Header_Culture", "Culture").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_Header_Culture", "Culture").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Culture> Culture1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_Header_Culture", "Culture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Culture>("lrModel.FK_Header_Culture", "Culture", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Header_Header", "HeaderClasses")]
        public HeaderClasses HeaderClasses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HeaderClasses>("lrModel.FK_Header_Header", "HeaderClasses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HeaderClasses>("lrModel.FK_Header_Header", "HeaderClasses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HeaderClasses> HeaderClassesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HeaderClasses>("lrModel.FK_Header_Header", "HeaderClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HeaderClasses>("lrModel.FK_Header_Header", "HeaderClasses", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="HeaderClasses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HeaderClasses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HeaderClasses object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="className">Initial value of the ClassName property.</param>
        public static HeaderClasses CreateHeaderClasses(global::System.Int32 id, global::System.String className)
        {
            HeaderClasses headerClasses = new HeaderClasses();
            headerClasses.Id = id;
            headerClasses.ClassName = className;
            return headerClasses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                OnClassNameChanging(value);
                ReportPropertyChanging("ClassName");
                _ClassName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClassName");
                OnClassNameChanged();
            }
        }
        private global::System.String _ClassName;
        partial void OnClassNameChanging(global::System.String value);
        partial void OnClassNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Header_Header", "Header")]
        public EntityCollection<Header> Header
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Header>("lrModel.FK_Header_Header", "Header");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Header>("lrModel.FK_Header_Header", "Header", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Menu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="page">Initial value of the Page property.</param>
        /// <param name="culture">Initial value of the Culture property.</param>
        public static Menu CreateMenu(global::System.Int32 id, global::System.String name, global::System.Int32 page, global::System.Int32 culture)
        {
            Menu menu = new Menu();
            menu.Id = id;
            menu.Name = name;
            menu.Page = page;
            menu.Culture = culture;
            return menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Page
        {
            get
            {
                return _Page;
            }
            set
            {
                OnPageChanging(value);
                ReportPropertyChanging("Page");
                _Page = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Page");
                OnPageChanged();
            }
        }
        private global::System.Int32 _Page;
        partial void OnPageChanging(global::System.Int32 value);
        partial void OnPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ItemOrder
        {
            get
            {
                return _ItemOrder;
            }
            set
            {
                OnItemOrderChanging(value);
                ReportPropertyChanging("ItemOrder");
                _ItemOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemOrder");
                OnItemOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _ItemOrder;
        partial void OnItemOrderChanging(Nullable<global::System.Int32> value);
        partial void OnItemOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Culture
        {
            get
            {
                return _Culture;
            }
            set
            {
                OnCultureChanging(value);
                ReportPropertyChanging("Culture");
                _Culture = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Culture");
                OnCultureChanged();
            }
        }
        private global::System.Int32 _Culture;
        partial void OnCultureChanging(global::System.Int32 value);
        partial void OnCultureChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Menu_PageRoute", "Culture")]
        public Culture Culture1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_Menu_PageRoute", "Culture").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_Menu_PageRoute", "Culture").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Culture> Culture1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_Menu_PageRoute", "Culture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Culture>("lrModel.FK_Menu_PageRoute", "Culture", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Menu_PageRoute1", "PageRoute")]
        public PageRoute PageRoute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageRoute>("lrModel.FK_Menu_PageRoute1", "PageRoute").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageRoute>("lrModel.FK_Menu_PageRoute1", "PageRoute").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PageRoute> PageRouteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageRoute>("lrModel.FK_Menu_PageRoute1", "PageRoute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PageRoute>("lrModel.FK_Menu_PageRoute1", "PageRoute", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="PageContentClasses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PageContentClasses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PageContentClasses object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="className">Initial value of the ClassName property.</param>
        public static PageContentClasses CreatePageContentClasses(global::System.Int32 id, global::System.String className)
        {
            PageContentClasses pageContentClasses = new PageContentClasses();
            pageContentClasses.Id = id;
            pageContentClasses.ClassName = className;
            return pageContentClasses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                OnClassNameChanging(value);
                ReportPropertyChanging("ClassName");
                _ClassName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClassName");
                OnClassNameChanged();
            }
        }
        private global::System.String _ClassName;
        partial void OnClassNameChanging(global::System.String value);
        partial void OnClassNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_PageContentClasses", "PageContents")]
        public EntityCollection<PageContents> PageContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PageContents>("lrModel.FK_PageContents_PageContentClasses", "PageContents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PageContents>("lrModel.FK_PageContents_PageContentClasses", "PageContents", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="PageContents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PageContents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PageContents object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pageId">Initial value of the PageId property.</param>
        /// <param name="cssClass">Initial value of the CssClass property.</param>
        /// <param name="changeTime">Initial value of the ChangeTime property.</param>
        /// <param name="pageType">Initial value of the PageType property.</param>
        public static PageContents CreatePageContents(global::System.Int32 id, global::System.Int32 pageId, global::System.Int32 cssClass, global::System.DateTime changeTime, global::System.Int32 pageType)
        {
            PageContents pageContents = new PageContents();
            pageContents.Id = id;
            pageContents.PageId = pageId;
            pageContents.CssClass = cssClass;
            pageContents.ChangeTime = changeTime;
            pageContents.PageType = pageType;
            return pageContents;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PageContent
        {
            get
            {
                return _PageContent;
            }
            set
            {
                OnPageContentChanging(value);
                ReportPropertyChanging("PageContent");
                _PageContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PageContent");
                OnPageContentChanged();
            }
        }
        private global::System.String _PageContent;
        partial void OnPageContentChanging(global::System.String value);
        partial void OnPageContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageId
        {
            get
            {
                return _PageId;
            }
            set
            {
                OnPageIdChanging(value);
                ReportPropertyChanging("PageId");
                _PageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageId");
                OnPageIdChanged();
            }
        }
        private global::System.Int32 _PageId;
        partial void OnPageIdChanging(global::System.Int32 value);
        partial void OnPageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CssClass
        {
            get
            {
                return _CssClass;
            }
            set
            {
                OnCssClassChanging(value);
                ReportPropertyChanging("CssClass");
                _CssClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CssClass");
                OnCssClassChanged();
            }
        }
        private global::System.Int32 _CssClass;
        partial void OnCssClassChanging(global::System.Int32 value);
        partial void OnCssClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ChangeTime
        {
            get
            {
                return _ChangeTime;
            }
            set
            {
                OnChangeTimeChanging(value);
                ReportPropertyChanging("ChangeTime");
                _ChangeTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChangeTime");
                OnChangeTimeChanged();
            }
        }
        private global::System.DateTime _ChangeTime;
        partial void OnChangeTimeChanging(global::System.DateTime value);
        partial void OnChangeTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageType
        {
            get
            {
                return _PageType;
            }
            set
            {
                OnPageTypeChanging(value);
                ReportPropertyChanging("PageType");
                _PageType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageType");
                OnPageTypeChanged();
            }
        }
        private global::System.Int32 _PageType;
        partial void OnPageTypeChanging(global::System.Int32 value);
        partial void OnPageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private Nullable<global::System.Int32> _Contact;
        partial void OnContactChanging(Nullable<global::System.Int32> value);
        partial void OnContactChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_Contact", "Contact")]
        public Contact Contact1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("lrModel.FK_PageContents_Contact", "Contact").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("lrModel.FK_PageContents_Contact", "Contact").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contact> Contact1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("lrModel.FK_PageContents_Contact", "Contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contact>("lrModel.FK_PageContents_Contact", "Contact", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_PageContentClasses", "PageContentClasses")]
        public PageContentClasses PageContentClasses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageContentClasses>("lrModel.FK_PageContents_PageContentClasses", "PageContentClasses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageContentClasses>("lrModel.FK_PageContents_PageContentClasses", "PageContentClasses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PageContentClasses> PageContentClassesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageContentClasses>("lrModel.FK_PageContents_PageContentClasses", "PageContentClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PageContentClasses>("lrModel.FK_PageContents_PageContentClasses", "PageContentClasses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_PageContentType", "PageContentType")]
        public PageContentType PageContentType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageContentType>("lrModel.FK_PageContents_PageContentType", "PageContentType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageContentType>("lrModel.FK_PageContents_PageContentType", "PageContentType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PageContentType> PageContentTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageContentType>("lrModel.FK_PageContents_PageContentType", "PageContentType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PageContentType>("lrModel.FK_PageContents_PageContentType", "PageContentType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_PageRoute", "PageRoute")]
        public PageRoute PageRoute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageRoute>("lrModel.FK_PageContents_PageRoute", "PageRoute").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageRoute>("lrModel.FK_PageContents_PageRoute", "PageRoute").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PageRoute> PageRouteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageRoute>("lrModel.FK_PageContents_PageRoute", "PageRoute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PageRoute>("lrModel.FK_PageContents_PageRoute", "PageRoute", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="PageContentType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PageContentType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PageContentType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pageType">Initial value of the PageType property.</param>
        public static PageContentType CreatePageContentType(global::System.Int32 id, global::System.String pageType)
        {
            PageContentType pageContentType = new PageContentType();
            pageContentType.Id = id;
            pageContentType.PageType = pageType;
            return pageContentType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PageType
        {
            get
            {
                return _PageType;
            }
            set
            {
                OnPageTypeChanging(value);
                ReportPropertyChanging("PageType");
                _PageType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PageType");
                OnPageTypeChanged();
            }
        }
        private global::System.String _PageType;
        partial void OnPageTypeChanging(global::System.String value);
        partial void OnPageTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_PageContentType", "PageContents")]
        public EntityCollection<PageContents> PageContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PageContents>("lrModel.FK_PageContents_PageContentType", "PageContents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PageContents>("lrModel.FK_PageContents_PageContentType", "PageContents", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="PageRoute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PageRoute : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PageRoute object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pageAddress">Initial value of the PageAddress property.</param>
        /// <param name="pageName">Initial value of the PageName property.</param>
        /// <param name="culture">Initial value of the Culture property.</param>
        public static PageRoute CreatePageRoute(global::System.Int32 id, global::System.String pageAddress, global::System.String pageName, global::System.Int32 culture)
        {
            PageRoute pageRoute = new PageRoute();
            pageRoute.Id = id;
            pageRoute.PageAddress = pageAddress;
            pageRoute.PageName = pageName;
            pageRoute.Culture = culture;
            return pageRoute;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PageAddress
        {
            get
            {
                return _PageAddress;
            }
            set
            {
                OnPageAddressChanging(value);
                ReportPropertyChanging("PageAddress");
                _PageAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PageAddress");
                OnPageAddressChanged();
            }
        }
        private global::System.String _PageAddress;
        partial void OnPageAddressChanging(global::System.String value);
        partial void OnPageAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PageName
        {
            get
            {
                return _PageName;
            }
            set
            {
                OnPageNameChanging(value);
                ReportPropertyChanging("PageName");
                _PageName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PageName");
                OnPageNameChanged();
            }
        }
        private global::System.String _PageName;
        partial void OnPageNameChanging(global::System.String value);
        partial void OnPageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Culture
        {
            get
            {
                return _Culture;
            }
            set
            {
                OnCultureChanging(value);
                ReportPropertyChanging("Culture");
                _Culture = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Culture");
                OnCultureChanged();
            }
        }
        private global::System.Int32 _Culture;
        partial void OnCultureChanging(global::System.Int32 value);
        partial void OnCultureChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageRoute_Culture", "Culture")]
        public Culture Culture1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_PageRoute_Culture", "Culture").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_PageRoute_Culture", "Culture").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Culture> Culture1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Culture>("lrModel.FK_PageRoute_Culture", "Culture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Culture>("lrModel.FK_PageRoute_Culture", "Culture", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_Menu_PageRoute1", "Menu")]
        public EntityCollection<Menu> Menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("lrModel.FK_Menu_PageRoute1", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("lrModel.FK_Menu_PageRoute1", "Menu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("lrModel", "FK_PageContents_PageRoute", "PageContents")]
        public EntityCollection<PageContents> PageContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PageContents>("lrModel.FK_PageContents_PageRoute", "PageContents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PageContents>("lrModel.FK_PageContents_PageRoute", "PageContents", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lrModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Users CreateUsers(global::System.Int32 id, global::System.String userName, global::System.String password)
        {
            Users users = new Users();
            users.Id = id;
            users.UserName = userName;
            users.Password = password;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }

    #endregion
    
}
